# Device specific substitutions
substitutions:
  node_id: "91"
  node_name: esphome91
  node_friendly_name: Btprxy (Test)
  node_comment: Esp32 C3 (BTPrxy) (VLAN IoT)
  log_level: INFO

packages:
  file: !include common/.board_esp32_c3.yaml
  proxy: !include common/.blueprint_bluetooth_proxy.yaml