substitutions:
  name: esphome87-101a00
  friendly_name: Voice Assistant 1 101a00
packages:
  m5stack.atom-echo-voice-assistant: github://esphome/firmware/voice-assistant/m5stack-atom-echo.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: 9Oh4+Y0d8DqXs+1dOHdTZ48l4u3wHJ2sHZXgZGQk8kI=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none