substitutions:
  name: m5stack-atom-echo-101a00
  friendly_name: M5Stack Atom Echo 101a00
  node_id: "xx"

packages:
  m5stack.atom-echo-voice-assistant: github://esphome/firmware/voice-assistant/m5stack-atom-echo.adopted.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: False
  friendly_name: ${friendly_name}

api:
  encryption:
    key: jVkfUtmHtLjN7HVWr76TNRTi6GG9xtQNga4zaQ4Qxv0=

wifi:
  networks:
  - ssid: !secret WIFI_SSID
    password: !secret WIFI_PWD
  fast_connect: false
  domain: .local
  power_save_mode: none
  manual_ip:
    static_ip: 192.168.0.1${node_id}
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    dns1: 192.168.0.1