# Loads default set of integrations. Do not remove.
default_config:

# Define global log-level
logger:
  default: info
# logger:
#   default: info
#   logs:
#     homeassistant.components.automation: debug

# MaraiaDB specific configuration
# recorder:
#   db_url: mysql://homeassistant:IceAgeRulesMDB@core-mariadb/homeassistant?charset=utf8mb4
#   purge_keep_days: 14
#   auto_purge: true
#   commit_interval: 30
#   exclude:
#     entities:
#       # Elmätare – fasström (behåll energi per timme/dag, rör ej!)
#       - sensor.elmatare_elstolpen_current_phase_1
#       - sensor.elmatare_elstolpen_current_phase_2
#       - sensor.elmatare_elstolpen_current_phase_3

recorder:
  db_url: mysql://homeassistant:IceAgeRulesMDB@core-mariadb/homeassistant?charset=utf8mb4
  auto_purge: true
  purge_keep_days: 5
  commit_interval: 5

  exclude:
    # Ta bort hela domäner som oftast skräpar
    domains:
      - persistent_notification
      - camera
      - image_processing
      - media_player
      - weather
      - updater

    # Generiska mönster (globbar) – inga hårdkodade namn
    entity_globs:
      # Tickande klock-/datum-/uptime-sensorer
      - sensor.time*
      - sensor.date*
      - sensor.uptime*

      # OpenWRT (alla sensorer från integrationen)
      - sensor.openwrt_*

      # ESPHome-lampor – högfrekvent brus (behåll ev. *_energy)
      - sensor.*_light_power
      - sensor.*_light_voltage
      - sensor.*_light_current

      # Elmätare: exkludera effekt/spänning (behåll energy/kWh för Energi)
      - sensor.elmatare_*_power*
      - sensor.elmatare_*_voltage*

      # System-/CPU-last etc.
      - sensor.system_monitor_load_*
      - sensor.processor_*

    # Brusiga eventtyper som sällan behövs i recorder
    event_types:
      - call_service
      - entity_registry_updated
      - service_registered
      - service_removed
      - component_loaded
      - logbook_entry
      - automation_triggered
      - automation_reloaded
      - recorder_5min_statistics_generated
      - recorder_hourly_statistics_generated
      - device_registry_updated
      - panels_updated
      - core_config_updated
      - lovelace_updated




# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/card-mod.js

# Load automations, scripts and scenes from separate files (System - do not move or alter)
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Load extra configurationes as described in separate files in dir packages/
homeassistant:
  packages: !include_dir_named packages
  allowlist_external_dirs:
    - /config/file_notifications
    
# Text to speech
tts:
  - platform: google_translate