packages:
  base: github://esphome/home-assistant-voice-pe/home-assistant-voice.yaml

micro_wake_word:
  models:
    - model: "https://raw.githubusercontent.com/j-k-olofsson/homeassistant/main/esphome/packages/models/hai_gran_nee/hai_gran_nee.json"
    # Om du valde alternativ B:
    # - model: "https://raw.githubusercontent.com/j-k-olofsson/ha-voice-models/main/hai_gran_nee/hai_gran_nee.json"

