# Root file for SonOff Basic Switch specific stuff

# Node info
esphome:
  name: ${node_name}
  comment: ${node_comment}
  friendly_name: ${node_friendly_name}

esp8266:
  board: esp8285
  framework:
    version: recommended

packages:
  device_base: !include .base.yaml

status_led:
  pin:
    number: GPIO13
    inverted: true

switch:
  - platform: gpio
    name: ${node_name} Relay State
    pin: GPIO12
    id: myRelay
    restore_mode: RESTORE_DEFAULT_ON
  - platform: restart
    id: myRestartSwitch
    internal: true

binary_sensor:
  - platform: gpio
    id: myButton
    internal: true
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_click:
      then:
        - switch.toggle: myRelay
    on_multi_click:
      - timing:
        - ON for at least 3s
        then:
          - switch.toggle: myRestartSwitch