# Board package for ESP32-C6-Zero over Thread

esphome:
  name: ${node_name}
  comment: ${node_comment}
  friendly_name: ${node_friendly_name}

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  flash_size: 8MB
  framework:
    type: esp-idf
    version: recommended
    advanced:
      include_builtin_idf_components:
        - openthread

packages:
  device_base: !include .base_thread.yaml

switch:
  - platform: restart
    id: myRestartSwitch
    internal: true