# Root file for ESP32DEV board specific stuff

# Node info
esphome:
  name: ${node_name}
  comment: ${node_comment}
  friendly_name: ${node_friendly_name}
  
esp32:
  board: esp32dev

packages:
  device_base: !include .base.yaml

switch:
  - platform: restart
    id: myRestartSwitch
    internal: true

# light:
#   - platform: status_led
#     id: myOnboardStatusLed
#     internal: true
#     name: ${node_name} Status LED
#     pin:
#       number: GPIO5
#       inverted: true