# Root file for SonOff Basic specific stuff

# Node info
esphome:
  name: ${node_name}
  comment: ${node_comment}
  friendly_name: ${node_friendly_name}

esp8266:
  board: esp8285
  framework:
    version: recommended

packages:
  device_base: !include .base.yaml

light:
  - platform: binary
    name: ${node_name} Light
    id: myLight
    output: myOutput
    restore_mode: RESTORE_DEFAULT_OFF

output:
  - platform: gpio
    pin: GPIO12
    id: myOutput
    
status_led:
  pin:
    number: GPIO13
    inverted: true

switch:
  - platform: restart
    id: myRestartSwitch
    internal: true

binary_sensor:
  - platform: gpio
    id: myButton
    internal: true
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - light.toggle: myLight
    on_double_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - switch.turn_on: myRestartSwitch