# Root file for SonOff RF Bridge 2 specific stuff

# Node info
esphome:
  name: ${node_name}
  comment: ${node_comment}
  friendly_name: ${node_friendly_name}
  
esp8266:
  board: esp8285
  framework:
    version: recommended

packages:
  device_base: !include .base.yaml

status_led:
  pin:
    number: GPIO13
    inverted: true

switch:
  - platform: restart
    id: myRestartSwitch
    internal: true