# Shared package for the VEML7700 ambient light sensor

sensor:
  - platform: veml7700
    i2c_id: ${sensor_i2c_bus_id}
    update_interval: ${veml7700_update_interval}
    ambient_light:
      name: ${node_name} Illuminance
      device_class: illuminance
      state_class: measurement
      accuracy_decimals: 1
    infrared:
      name: ${node_name} Infrared
      accuracy_decimals: 1
    integration_time: 100ms
    gain: 1X
