# Device specific substitutions
substitutions:
  node_id: "42"
  node_name: esphome42
  node_friendly_name: Ledstrip (vitrinskåp)
  node_comment: Lolin32 (VLAN IoT)
  log_level: INFO
  num_leds: "107"
  gpio_pin: "GPIO13"
  night_brightness: "20%"
  day_brightness: "40%"

# Include packages for this device specific type
packages:
  file: !include common/.device_lolin32_ledstrip_indoors.yaml