# Device specific substitutions
substitutions:
  node_id: "45"
  node_name: esphome45
  node_friendly_name: Ledstrip (toalett)
  node_comment: Lolin32 (VLAN IoT)
  log_level: INFO
  num_leds: "50"
  gpio_pin: "GPIO13"
  night_brightness: "30%"

# Include packages for this device specific type
packages:
 file: !include common/.device_lolin32_ledstrip_window.yaml