# Substitutions
substitutions:
  node_id: "60"
  node_name: esphome60
  node_friendly_name: Taklampor (köket)
  node_comment: Shelly Dimmer 2
  log_level: INFO
  stm_fw_update: "false"
  node_min_brightness: "440"
  node_preset_tripple_tap: "1%"
  transition_period: 1500ms

packages:
  file: !include common/.device_shelly_dimmer_2.yaml