# Device specific substitutions
substitutions:
  node_id: "02"
  node_name: esphome02
  node_friendly_name: Blomlampa (trappan)
  node_comment: Sonoff Basic (VLAN IoT)
  log_level: INFO
  late_on: "true"

# Include packages for this device specific type
packages:
  file: !include common/.device_sonoff_basic_flower_light.yaml