# Device specific substitutions
substitutions:
  node_id: "96"
  node_name: esphome96
  node_friendly_name: IR-proxy 1
  node_comment: M5Stack ATOM Lite + IR Unit U002 (VLAN IoT)
  log_level: INFO

# Include packages for this device specific type
packages:
  file: !include common/.device_m5stack_atom_lite_ir_proxy.yaml

button:
  - platform: template
    name: "IR-proxy 1 Candle ON"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0x93CB
          command: 0xAF50

  - platform: template
    name: "IR-proxy 1 Candle OFF"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0x93CB
          command: 0xA05F
