# Device specific substitutions
substitutions:
  node_id: "41"
  node_name: esphome41
  node_friendly_name: Ledstrip (entrén)
  node_comment: Lolin32 (VLAN IoT)
  log_level: INFO
  num_leds: "141"
  gpio_pin: GPIO13
  night_brightness: 40%
  doppler_pin: GPIO14

# Include packages for this device specific type
packages:
  file: !include common/.device_lolin32_ledstrip_window.yaml

binary_sensor:
  - platform: gpio
    id: myDoppler
    internal: true
    pin:
      number: ${doppler_pin}
      mode:
        input: true
        pulldown: true
    name: ${node_name} Motion Sensor
    device_class: motion
    filters:
      - delayed_on: 500ms
      - delayed_off: 10s
    on_press:
      then:
        - light.turn_on:
            id: led_rgb
            effect: "None"
        - light.turn_on:
            id: led_rgb
            brightness: 100%
            red: 100%
            green: 100%
            blue: 100%
            transition_length: 1s
    on_release:
      then:
        - switch.turn_on: myRelay