# Device specific substitutions
substitutions:
  node_id: "09"
  node_name: esphome09
  node_friendly_name: Blomlampa (ateljén)
  node_comment: Sonoff Basic (VLAN IoT)
  log_level: INFO
  late_on: "false"

# Include packages for this device specific type
packages:
  file: !include common/.device_sonoff_basic_flower_light.yaml