# Device specific substitutions
substitutions:
  node_id: "58"
  node_name: esphome58
  node_friendly_name: Ledstrip (korridoren)
  node_comment: Esp32 D1 mini (VLAN IoT)
  log_level: INFO
  num_leds: "46"
  gpio_pin: "GPIO16"
  night_brightness: "20%"
  day_brightness: "40%"
  # kill_button_pin: GPIO27

# Include packages for this device specific type
packages:
  ledstrip: !include common/.device_d1_mini32_ledstrip_indoors.yaml
  # killbutton: !include common/.blueprint_ledstrip_kill_button.yaml

safe_mode:

switch:
  - platform: safe_mode
    name: "${node_name} switch Restart (Safe Mode)"
    internal: True