# Device specific substitutions
substitutions:
  node_id: "98"
  node_name: esphome98
  node_friendly_name: Ljussensor
  node_comment: ESP32-C3 (lux/UV sensor) (VLAN IoT)
  log_level: DEBUG
  veml7700_sda_pin: GPIO5
  veml7700_scl_pin: GPIO6
  veml6075_sda_pin: GPIO7
  veml6075_scl_pin: GPIO10
  veml7700_update_interval: 30s
  uv_update_interval: 10s

# Include packages for this device specific type
packages:
  board: !include common/.board_esp32_c3_arduino.yaml
  sensors: !include common/.device_lolin32_lux_uv.yaml
