# Device specific substitutions
substitutions:
  node_id: "24"
  node_name: esphome24
  node_friendly_name: Bilvärmare (utomhus)
  node_comment: Sonoff S55 (VLAN IoT)
  log_level: INFO

# Include packages for this device specific type
packages:
  file: !include common/.device_sonoff_basic_switch.yaml