# Test-only config for esphome42.
# Do not deploy to production unless the rollback issue is confirmed fixed.
substitutions:
  node_id: "42"
  node_name: esphome42
  node_friendly_name: Ledstrip (vitrinskåp)
  node_comment: Lolin32 (VLAN IoT) RMT test track
  log_level: INFO
  num_leds: "107"
  gpio_pin: "GPIO13"
  night_brightness: "20%"
  day_brightness: "40%"

packages:
  file: !include common/.device_lolin32_ledstrip_indoors_rmt_test.yaml

safe_mode:
