# Substitutions
substitutions:
  node_id: "56"
  node_name: esphome56
  node_friendly_name: Kökslampor (kök)
  node_comment: Shelly Dimmer 2 (VLAN IoT)
  log_level: INFO
  stm_fw_update: "true"
  node_min_brightness: "50"
  node_preset_tripple_tap: "1%"
  transition_period: 3s

packages:
  file: !include common/.device_shelly_dimmer_2.yaml