# Device specific substitutions
substitutions:
  node_id: "08"
  node_name: esphome08
  node_friendly_name: Ventilfläkt (källaren)
  node_comment: Sonoff Basic as Fan (VLAN IoT)
  log_level: INFO

# Include packages for this device specific type
# packages:
#   file: !include common/.device_sonoff_basic_switch.yaml

# Root file for SonOff Basic Switch specific stuff

# Node info
esphome:
  name: ${node_name}
  comment: ${node_comment}
  friendly_name: ${node_friendly_name}

esp8266:
  board: esp8285
  framework:
    version: recommended

packages:
  device_base: !include common/.base.yaml

status_led:
  pin:
    number: GPIO13
    inverted: true

switch:
  - platform: restart
    id: myRestart

binary_sensor:
  - platform: gpio
    id: myButton
    internal: true
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - fan.toggle: myFan
    on_double_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - switch.turn_on: myRestart

output:
  - platform: gpio
    pin: GPIO12
    id: myRelay

fan:
  - platform: binary
    output: myRelay
    name: ${node_name} Fan
    id: myFan
    restore_mode: RESTORE_DEFAULT_OFF