# Device specific substitutions
substitutions:
  node_id: "80"
  node_name: esphome80
  node_friendly_name: Golvvärme (friggan)
  node_comment: Sonoff POW2 (VLAN IoT)
  log_level: INFO

# Include packages for this device specific type
packages:
  file: !include common/.device_sonoff_pow2.yaml