# Device specific substitutions
substitutions:
  node_id: "46"
  node_name: esphome46
  node_friendly_name: Ledstrip (ateljé norra)
  node_comment: ESP32-C6-Zero over Thread
  log_level: INFO
  num_leds: "50"
  gpio_pin: "GPIO3"
  night_brightness: "60%"

packages:
  device: !include common/.device_esp32_c6_thread_ledstrip_window.yaml
