# Substitutions
substitutions:
  node_id: "61"
  node_name: esphome61
  node_friendly_name: Taklampor (kontoret)
  node_comment: Shelly Dimmer 2
  log_level: INFO
  stm_fw_update: "false"
  node_min_brightness: "550"
  node_preset_tripple_tap: "1%"
  transition_period: 1s

packages:
  file: !include common/.device_shelly_dimmer_2.yaml