# Device specific substitutions
substitutions:
  node_id: "30"
  node_name: esphome30
  node_friendly_name: "Hemmabio El #1"
  node_comment: Sonoff PowR3 16D Elite (VLAN IoT)
  log_level: INFO

# Include packages for this device specific type
packages:
  file: !include common/.device_sonoff_powr316d.yaml