# Substitutions
substitutions:
  node_id: "55"
  node_name: esphome55
  node_friendly_name: Bordlampor (kök)
  node_comment: Shelly Dimmer 2 (VLAN IoT)
  log_level: INFO
  stm_fw_update: "false"
  node_min_brightness: "200"
  node_preset_tripple_tap: "1%"
  transition_period: 3s

packages:
  file: !include common/.device_shelly_dimmer_2.yaml