substitutions:
  name: home-assistant-voice-096460
  friendly_name: HA Voice PE 096460

# Byt från GitHub-paketet till din lokala kopia:
packages:
  voice_pe: !include packages/home-assistant-voice.yaml

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: mtTivd9Buk2BkbIF2bae6RPJPXCWKnRkYf+el3o8JAA=

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password